### ISSUE TITLE
Should document or depend on "tessel"

### ISSUE THREAD

**Issue by cprima** [johnnyman727/rgb-tcs34725#5]
As I was looking for a JS implementation of those many Python scripts I came across this code.

Unfortuanetely I cannot figure out what the first line of code requires -- "tessel".
The tessel.io website also did not give me such a module.

The description in the readme doesn"t say it is hardware-specific. But my RPi Zero with Johnny-Five and Raspi-io doesn't wirk with this code.

To adapt this code I's like to find a pointer to "require tessel" so I can figure out an adaptation.

Please point me to the required module.

**Comment by johnnyman727** [comment]
Hi @cprior,

This implementation is dependent on using Tessel hardware (I've edited the description to make that explicit). The `tessel` module is included by default when you use Tessel hardware, that is why you won't be able to find it on `npm`. This library likely will not work on hardware that is not Tessel.
